### ISSUE TITLE
error in example

### ISSUE THREAD

**Issue by bumble812** [celloza/ucm-psmodule#1]
instead of 

$md5token = $tokenstring.Replace("-","").ToLower()

it should be

$md5token = $hash.Replace("-","").ToLower()

**Comment by bumble812** [comment]
Thank you very much, Marcell. Without your example I would have suffered for a long time, because the tokenstring structure is not clearly documented anywhere.

**Comment by celloza** [comment]
@bumble812 np! 😄 

Now that I see it'll be more than just me that uses it, I'll implement the rest of the 80-odd methods.
